dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - linux
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
install:
  - yarn
script:
  - yarn run lint
  - yarn run test -- --watch=false
  - yarn run e2e
notifications:
  email:
    recipients:
      - Vincentwc_Huang@asus.com
    on_success: always
    on_failure: always
cache: yarn